### PR TITLE
update ntp to 4.2.8p15 from 4.2.8p8

### PR DESCRIPTION
**Pull request by tozhu**
update ntp from 4.2.8p8 to  4.2.8p15, has already compiled and no issue found

### CODE REVIEW

**Comment by tozhu** [comment]
testing progress, and screen dump

1. with the NTP changes, compile an smartos image and the usb image
====================================================

Building version files                                                                                                                                                                      ... done
Generating shipped file manifest                                                                                                                                                            ... done (5s)
Fixing shipped files                                                                                                                                                                        ... done
Compressing /usr image to include in root image                                                                                                                                             ... done (28s)
Finishing boot_archive creation                                                                                                                                                             ... done (4s)
Creating platform tar archive                                                                                                                                                               ... done (22s)
  * Linked build output: "platform-latest -> platform-20201217T131755Z"
  * Linked build output: "platform-latest.tgz -> platform-20201217T131755Z.tgz"
Removing temporary directory...                                                                                                                                                             ... done
./tools/build_boot_image -r /home/tony/my_osdev
Creating EFI System Partition image ... done
Creating 2 GB image at /var/tmp/tmp.9DGMib/hunghuos.usb ... done
partition.map:
loader 12 1048576 268435456
boot 1 269484032 1048576
root 2 270532608 7720665088
reserved 11 7991594496 8388608
Creating PCFS filesystem in root partition ... done
Mounting root partition at /var/tmp/tmp.9DGMib/mnt/root ... done
Installing boot tarball onto root partition ... done
Customizing boot loader configuration ... done
Copying platform image to root partition (this will take a while) ... done
Copying root filesystem ...
7363+0 records in
7363+0 records out
7720665088 bytes transferred in 80.654945 secs (91.3MB/sec)
done
Compressing USB image ...
Successfully created /home/tony/my_osdev/output-usb/platform-20201217T131755Z.usb.gz
Cleaning up
[tony@hosdev ~/my_osdev]$ scp /home/tony/my_osdev/output-usb/platform-20201217T131755Z.usb.gz root@10.10.0.111:/zones



2. dd the image into USB disk
=======================================
[root@dell1u ~]# diskinfo
TYPE    DISK                    VID      PID              SIZE          RMV SSD
SATA    c1t0d0                  APPLE    SSD SM0128G       113.00 GiB   no  yes
SCSI    c2t0d0                  SanDisk  Cruzer Edge         7.45 GiB   yes no
SATA    c3t0d0                  TOSHIBA  DT01ACA100        931.51 GiB   no  no
SATA    c3t1d0                  TOSHIBA  DT01ACA100        931.51 GiB   no  no
[root@dell1u ~]# zpool list -v
NAME         SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
zones        928G   260G   668G        -         -    11%    27%  1.00x  ONLINE  -
  mirror     928G   260G   668G        -         -    11%  28.0%
    c3t0d0      -      -      -        -         -      -      -
    c3t1d0      -      -      -        -         -      -      -
cache           -      -      -         -      -      -
  c1t0d0     113G  1.08G   112G        -         -     0%  0.95%
[root@dell1u ~]# diskinfo |grep SanDisk
SCSI    c2t0d0                  SanDisk  Cruzer Edge         7.45 GiB   yes no

[root@dell1u ~]# time cat /zones/platform-20201217T131755Z.usb.gz |gzip -d - | dd of=/dev/rdsk/c2t0d0p0 bs=4096k
0+244142 records in
0+244142 records out
8000000000 bytes transferred in 677.495762 secs (11.3MB/sec)

real	11m17.478s
user	1m59.551s
sys	0m17.756s
[root@dell1u ~]#

3. check current ntp software version, and its function. 
=============================================================
[root@dell1u ~]# ntpd -v
/usr/sbin/ntpd: illegal option -- v
ntpd - NTP daemon program - Ver. 4.2.8p8
Usage:  ntpd [ -<flag> [<val>] | --<name>[{=| }<val>] ]... \
                [ <server1> ... <serverN> ]
Try 'ntpd --help' for more information.
[root@dell1u ~]#

[root@dell1u ~]# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 1.cn.pool.ntp.o .POOL.          16 p    -   16    0    0.000    0.000   0.000
+111.230.189.174 100.122.36.4     2 u  838 1024  377   40.081    1.460   3.905
-ntp5.flashdance 192.36.143.130   2 u   31 1024  377  274.316   27.175   4.546
+a.chl.la        131.188.3.222    2 u  502 1024  337  186.421    1.971   8.423
+electrode.felix 56.1.129.236     3 u  228 1024   37  166.891    3.975   9.307
*tick.ntp.infoma .GPS.            1 u  222 1024  377  167.404    2.701   3.302
+tock.ntp.infoma .GPS.            1 u  552 1024  377  184.853   -0.003   6.958
-ntp.xtom.nl     131.176.107.13   2 u  706 1024  377  197.725   13.500   9.753
-time.cloudflare 10.12.2.186      3 u  383 1024  377  262.496  -39.638   3.982
-ntp8.flashdance 192.36.143.130   2 u  858 1024  377  332.893   49.360  13.351
[root@dell1u ~]#
[root@dell1u ~]#
[root@dell1u ~]# ntpq -v
/usr/sbin/ntpq: illegal option -- v
ntpq - standard NTP query program - Ver. 4.2.8p8
Usage:  ntpq [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [ host ...]
Try 'ntpq --help' for more information.
[root@dell1u ~]#


4. reboot the machine, after it back, and check the ntp version and function
=========================================================
[root@dell1u ~]# shutdown -i6 -g0 -y

Shutdown started.    Fri Dec 18 04:39:32 UTC 2020

Broadcast Message from root (pts/1) on dell1u Fri Dec 18 04:39:32...
THE SYSTEM dell1u IS BEING SHUT DOWN NOW ! ! !
Log off now or risk your files being damaged

Changing to init state 6 - please wait
[root@dell1u ~]#



[root@dell1u ~]# ntpd -v
/usr/sbin/ntpd: illegal option -- v
ntpd - NTP daemon program - Ver. 4.2.8p15
Usage:  ntpd [ -<flag> [<val>] | --<name>[{=| }<val>] ]... \
                [ <server1> ... <serverN> ]
Try 'ntpd --help' for more information.
[root@dell1u ~]# ntpq -v
/usr/sbin/ntpq: illegal option -- v
ntpq - standard NTP query program - Ver. 4.2.8p15
Usage:  ntpq [ -<flag> [<val>] | --<name>[{=| }<val>] ]... [ host ...]
Try 'ntpq --help' for more information.
[root@dell1u ~]#
[root@dell1u ~]# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 1.cn.pool.ntp.o .POOL.          16 p    -   16    0    0.000   +0.000   0.000
-time.cloudflare 10.12.2.186      3 u   81   64  356  247.143  -37.107   2.902
+ntp.xtom.nl     193.79.237.14    2 u   18   32  377  183.430   +4.269   2.907
*119.28.206.193  100.122.36.196   2 u   12   32  377   45.283   -8.176   0.508
+94.130.49.186 ( 195.13.23.5      3 u   27   32  377  176.881   -4.825   0.572
[root@dell1u ~]#
[root@dell1u ~]#


5. ssss

**Comment by danmcd** [comment]
Thank you!  I'll be doing the following today:

1.) Opening an OS bug.
2.) Copying your test notes there for redundancy.
3.) Running a build myself.
4.) Assuming the build is successful like yours, pulling this in.

**Comment by danmcd** [comment]
https://smartos.org/bugview/OS-8256

**Review by danmcd — APPROVED** [review]

**Comment by danmcd** [comment]
Need to finish steps 3 and 4.

**Pull request merged**
