### PR TITLE
OS-8246 Put -lssp first in Perl builds

### PR DESCRIPTION
**Pull request by danmcd**
Prerequisite for upcoming stack-protection changes in illumos.

### CODE REVIEW

**Review by bahamat — APPROVED** [review]

**Comment by jclulow** [comment]
Is there some analysis for why this is necessary?  Are we going to break a lot of software builds?

**Comment by danmcd** [comment]
There is.  I was just teasing it out on chat.  Watch for it soon.

**Review by jasonbking — APPROVED** [review]

**Comment by danmcd** [comment]
> There is. I was just teasing it out on chat. Watch for it soon.

I've put text in the bug report:  https://smartos.org/bugview/OS-8246

**Comment by danmcd** [comment]
Testing notes updated in ticket.

**Pull request merged**
