### PR TITLE
OS-8348 platform node needs fix for illumos#3729

### PR DESCRIPTION
**Pull request by danmcd**
Needs building and testing still.

### CODE REVIEW

**Review by papertigers — APPROVED** [review]
Approving based on it being the same upstream patch.
Ping again once built and tested.  Or if you need help testing.

Side note...we may wish to investigate some other places we provide node.  I know we have node prebuilt that gets used in Jenkins jobs. Not sure where those are built or where they come from.

**Comment by papertigers** [comment]
Example: https://github.com/joyent/sdc-vm-agent/blob/master/Makefile#L19
This one is node v6 which should have the upstream patch in it.  So we need to be aware of ones that use something older.  Maybe @bahamat has more information on that env.

**Comment by danmcd** [comment]
Testing part 1:  post-compilation binary analysis.

Using `dis -F uv_interface_addresses /path/to/node` I compared both pre-and-post-this-fix disassemblies.

Before changes:
```
   uv_interface_addresses+0x58:  66 83 39 20        cmpw   $0x20,(%ecx)  /* 0x20 == 32 == PF_PACKET, continue if set */
   uv_interface_addresses+0x5c:  74 e2              je     -0x1e      <uv_interface_addresses+0x40>
   uv_interface_addresses+0x5e:  83 c0 01           addl   $0x1,%eax
   uv_interface_addresses+0x61:  89 03              movl   %eax,(%ebx)
   uv_interface_addresses+0x63:  8b 12              movl   (%edx),%edx
   uv_interface_addresses+0x65:  85 d2              testl  %edx,%edx
```

After changes:
```
   uv_interface_addresses+0x5b:  66 83 f9 02        cmpw   $0x2,%cx  /* 2 == AF_INET, jump out if set... */
   uv_interface_addresses+0x5f:  74 06              je     +0x6       <uv_interface_addresses+0x67>
   uv_interface_addresses+0x61:  66 83 f9 1a        cmpw   $0x1a,%cx /* 0x1a == 26 == AF_INET6, continue if not set. */
   uv_interface_addresses+0x65:  75 d9              jne    -0x27      <uv_interface_addresses+0x40>
   uv_interface_addresses+0x67:  83 c0 01           addl   $0x1,%eax
   uv_interface_addresses+0x6a:  89 03              movl   %eax,(%ebx)
   uv_interface_addresses+0x6c:  8b 12              movl   (%edx),%edx
   uv_interface_addresses+0x6e:  85 d2              testl  %edx,%edx
```

**Comment by danmcd** [comment]
Testing part 2:  Unpatched and patched runs of /usr/{fw,img,vm}/test/runtests on what should be a pristine-ish SmartOS VM.

Both failed equally, the only difference was a noteworthy increase in runtime (possibly due to some other factor?):

```
kebe(~)[1]% diff -u /tmp/{before,after}
--- /tmp/before	2022-01-31 19:27:43.000000000 -0500
+++ /tmp/after	2022-01-31 19:28:00.000000000 -0500
@@ -6,22 +6,23 @@
 /test/integration/enable-disable.test.js
 
 # test results:
-# Completed in 68 seconds.
+# Completed in 82 seconds.
 # PASS: 97 / 134
 # FAIL: 37 / 134
 
 
 IMG...
 
-
-FAILURES: 1/191 assertions failed (1559159ms)
+FAILURES: 1/193 assertions failed (1562834ms)
 error 1 (run 'TRACE=1 /usr/img/test/runtests' for more info)
+[root@coal ~]# 
 
 
 VM...
 
 #
-#  TEST COMPLETE IN 128 SECONDS, SUMMARY:
+#  TEST COMPLETE IN 285 SECONDS, SUMMARY:
 #
 # PASS: 0 / 0
+#
 ```

**Comment by danmcd** [comment]
Testing part 2a:  Repeate with-patch, noticed more reasonable times (73 secs for FW, and 125 secs for VM).

**Comment by danmcd** [comment]
I will leave it up to the reviewers whether or not I should drop in illumos#3729 to an experimental PI to make sure it copes with the newer illumos changes in getifaddrs().

**Comment by papertigers** [comment]
+IA
Thanks for the testing!

**Pull request merged**
